# Generated by Django 4.1.6 on 2023-02-03 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='사용 금액')),
                ('content', models.TextField(max_length=500, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가계부 생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='가계부 수정 시간')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='고객')),
            ],
            options={
                'db_table': 'accountbook',
                'ordering': ['-created_at'],
            },
        ),
    ]
